import '../core/model/autogenerated.dart';

class JsonParsers {
  static T fromJson<T>(Map<String, dynamic> json) {
    if (T == Autogenerated) {
      return Autogenerated.fromJson(json) as T;
    } else if (T == Map<String, dynamic>) {
      return json as T;
    } else {
      throw Exception('Unsupported type $T');
    }
  }
}
