class Autogenerated {
  String? id;
  String? role;
  String? status;
  Personal? personal;
  Location? location;
  Account? account;

  Autogenerated(
      {this.id,
        this.role,
        this.status,
        this.personal,
        this.location,
        this.account});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    role = json['role'];
    status = json['status'];
    personal = json['personal'] != null
        ? new Personal.fromJson(json['personal'])
        : null;
    location = json['location'] != null
        ? new Location.fromJson(json['location'])
        : null;
    account =
    json['account'] != null ? new Account.fromJson(json['account']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['role'] = this.role;
    data['status'] = this.status;
    if (this.personal != null) {
      data['personal'] = this.personal!.toJson();
    }
    if (this.location != null) {
      data['location'] = this.location!.toJson();
    }
    if (this.account != null) {
      data['account'] = this.account!.toJson();
    }
    return data;
  }
}

class Personal {
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? profileImageUrl;
  String? dateOfBirth;
  String? gender;

  Personal(
      {this.firstName,
        this.lastName,
        this.email,
        this.phone,
        this.profileImageUrl,
        this.dateOfBirth,
        this.gender});

  Personal.fromJson(Map<String, dynamic> json) {
    firstName = json['firstName'];
    lastName = json['lastName'];
    email = json['email'];
    phone = json['phone'];
    profileImageUrl = json['profileImageUrl'];
    dateOfBirth = json['dateOfBirth'];
    gender = json['gender'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['profileImageUrl'] = this.profileImageUrl;
    data['dateOfBirth'] = this.dateOfBirth;
    data['gender'] = this.gender;
    return data;
  }
}

class Location {
  String? country;
  String? state;
  String? city;
  String? timezone;

  Location({this.country, this.state, this.city, this.timezone});

  Location.fromJson(Map<String, dynamic> json) {
    country = json['country'];
    state = json['state'];
    city = json['city'];
    timezone = json['timezone'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this.country;
    data['state'] = this.state;
    data['city'] = this.city;
    data['timezone'] = this.timezone;
    return data;
  }
}

class Account {
  bool? isEmailVerified;
  bool? isPhoneVerified;
  String? signupMethod;
  String? lastLoginAt;
  String? createdAt;

  Account(
      {this.isEmailVerified,
        this.isPhoneVerified,
        this.signupMethod,
        this.lastLoginAt,
        this.createdAt});

  Account.fromJson(Map<String, dynamic> json) {
    isEmailVerified = json['isEmailVerified'];
    isPhoneVerified = json['isPhoneVerified'];
    signupMethod = json['signupMethod'];
    lastLoginAt = json['lastLoginAt'];
    createdAt = json['createdAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['isEmailVerified'] = this.isEmailVerified;
    data['isPhoneVerified'] = this.isPhoneVerified;
    data['signupMethod'] = this.signupMethod;
    data['lastLoginAt'] = this.lastLoginAt;
    data['createdAt'] = this.createdAt;
    return data;
  }
}